export type RoomLocaleRegion =
  | "popular"
  | "americas"
  | "europe"
  | "asia"
  | "africa"
  | "middle-east"
  | "oceania";

export type RoomLocaleOption = {
  id: string;
  nativeLabel: string;
  englishLabel: string;
  flag: string;
  region: RoomLocaleRegion;
};

/** ISO 639-1 + common regional tags — grouped for the room locale picker. */
const languageRows: Array<[id: string, native: string, english: string, flag: string, region: RoomLocaleRegion]> = [
  ["en-GB", "English (UK)", "English (UK)", "🇬🇧", "popular"],
  ["en", "English", "English", "🌍", "popular"],
  ["es-CO", "Español (Colombia)", "Spanish (Colombia)", "🇨🇴", "popular"],
  ["es", "Español", "Spanish", "🇪🇸", "popular"],
  ["es-MX", "Español (México)", "Spanish (Mexico)", "🇲🇽", "popular"],
  ["es-AR", "Español (Argentina)", "Spanish (Argentina)", "🇦🇷", "popular"],
  ["pt-BR", "Português (Brasil)", "Portuguese (Brazil)", "🇧🇷", "popular"],
  ["pt", "Português", "Portuguese", "🇵🇹", "popular"],
  ["fr", "Français", "French", "🇫🇷", "popular"],
  ["fr-CA", "Français (Canada)", "French (Canada)", "🇨🇦", "popular"],
  ["de", "Deutsch", "German", "🇩🇪", "popular"],
  ["it", "Italiano", "Italian", "🇮🇹", "popular"],
  ["nl", "Nederlands", "Dutch", "🇳🇱", "popular"],
  ["zh-CN", "中文 (简体)", "Chinese (Simplified)", "🇨🇳", "popular"],
  ["zh-TW", "中文 (繁體)", "Chinese (Traditional)", "🇹🇼", "popular"],
  ["ja", "日本語", "Japanese", "🇯🇵", "popular"],
  ["ko", "한국어", "Korean", "🇰🇷", "popular"],
  ["hi", "हिन्दी", "Hindi", "🇮🇳", "popular"],
  ["ar", "العربية", "Arabic", "🇸🇦", "popular"],
  ["ru", "Русский", "Russian", "🇷🇺", "popular"],
  ["tr", "Türkçe", "Turkish", "🇹🇷", "popular"],
  ["pl", "Polski", "Polish", "🇵🇱", "popular"],
  ["uk", "Українська", "Ukrainian", "🇺🇦", "popular"],
  ["vi", "Tiếng Việt", "Vietnamese", "🇻🇳", "popular"],
  ["th", "ไทย", "Thai", "🇹🇭", "popular"],
  ["id", "Bahasa Indonesia", "Indonesian", "🇮🇩", "popular"],
  ["ms", "Bahasa Melayu", "Malay", "🇲🇾", "popular"],
  ["sw", "Kiswahili", "Swahili", "🇰🇪", "popular"],
  ["en-US", "English (US)", "English (US)", "🇺🇸", "americas"],
  ["en-CA", "English (Canada)", "English (Canada)", "🇨🇦", "americas"],
  ["en-JM", "English (Jamaica)", "English (Jamaica)", "🇯🇲", "americas"],
  ["en-TT", "English (Trinidad)", "English (Trinidad)", "🇹🇹", "americas"],
  ["es-CL", "Español (Chile)", "Spanish (Chile)", "🇨🇱", "americas"],
  ["es-PE", "Español (Perú)", "Spanish (Peru)", "🇵🇪", "americas"],
  ["es-VE", "Español (Venezuela)", "Spanish (Venezuela)", "🇻🇪", "americas"],
  ["es-EC", "Español (Ecuador)", "Spanish (Ecuador)", "🇪🇨", "americas"],
  ["es-BO", "Español (Bolivia)", "Spanish (Bolivia)", "🇧🇴", "americas"],
  ["es-PY", "Español (Paraguay)", "Spanish (Paraguay)", "🇵🇾", "americas"],
  ["es-UY", "Español (Uruguay)", "Spanish (Uruguay)", "🇺🇾", "americas"],
  ["es-CU", "Español (Cuba)", "Spanish (Cuba)", "🇨🇺", "americas"],
  ["es-DO", "Español (Rep. Dominicana)", "Spanish (Dominican Republic)", "🇩🇴", "americas"],
  ["es-PR", "Español (Puerto Rico)", "Spanish (Puerto Rico)", "🇵🇷", "americas"],
  ["es-GT", "Español (Guatemala)", "Spanish (Guatemala)", "🇬🇹", "americas"],
  ["es-HN", "Español (Honduras)", "Spanish (Honduras)", "🇭🇳", "americas"],
  ["es-NI", "Español (Nicaragua)", "Spanish (Nicaragua)", "🇳🇮", "americas"],
  ["es-CR", "Español (Costa Rica)", "Spanish (Costa Rica)", "🇨🇷", "americas"],
  ["es-PA", "Español (Panamá)", "Spanish (Panama)", "🇵🇦", "americas"],
  ["pt-PT", "Português (Portugal)", "Portuguese (Portugal)", "🇵🇹", "americas"],
  ["ht", "Kreyòl ayisyen", "Haitian Creole", "🇭🇹", "americas"],
  ["qu", "Runa Simi", "Quechua", "🇵🇪", "americas"],
  ["gn", "Avañe'ẽ", "Guarani", "🇵🇾", "americas"],
  ["nl-BE", "Nederlands (België)", "Dutch (Belgium)", "🇧🇪", "europe"],
  ["fr-BE", "Français (Belgique)", "French (Belgium)", "🇧🇪", "europe"],
  ["de-AT", "Deutsch (Österreich)", "German (Austria)", "🇦🇹", "europe"],
  ["de-CH", "Deutsch (Schweiz)", "German (Switzerland)", "🇨🇭", "europe"],
  ["fr-CH", "Français (Suisse)", "French (Switzerland)", "🇨🇭", "europe"],
  ["it-CH", "Italiano (Svizzera)", "Italian (Switzerland)", "🇨🇭", "europe"],
  ["ca", "Català", "Catalan", "🇪🇸", "europe"],
  ["gl", "Galego", "Galician", "🇪🇸", "europe"],
  ["eu", "Euskara", "Basque", "🇪🇸", "europe"],
  ["cy", "Cymraeg", "Welsh", "🏴󠁧󠁢󠁷󠁬󠁳󠁿", "europe"],
  ["ga", "Gaeilge", "Irish", "🇮🇪", "europe"],
  ["gd", "Gàidhlig", "Scottish Gaelic", "🏴󠁧󠁢󠁳󠁣󠁴󠁿", "europe"],
  ["is", "Íslenska", "Icelandic", "🇮🇸", "europe"],
  ["da", "Dansk", "Danish", "🇩🇰", "europe"],
  ["sv", "Svenska", "Swedish", "🇸🇪", "europe"],
  ["nb", "Norsk Bokmål", "Norwegian Bokmål", "🇳🇴", "europe"],
  ["nn", "Norsk Nynorsk", "Norwegian Nynorsk", "🇳🇴", "europe"],
  ["fi", "Suomi", "Finnish", "🇫🇮", "europe"],
  ["et", "Eesti", "Estonian", "🇪🇪", "europe"],
  ["lv", "Latviešu", "Latvian", "🇱🇻", "europe"],
  ["lt", "Lietuvių", "Lithuanian", "🇱🇹", "europe"],
  ["cs", "Čeština", "Czech", "🇨🇿", "europe"],
  ["sk", "Slovenčina", "Slovak", "🇸🇰", "europe"],
  ["hu", "Magyar", "Hungarian", "🇭🇺", "europe"],
  ["ro", "Română", "Romanian", "🇷🇴", "europe"],
  ["bg", "Български", "Bulgarian", "🇧🇬", "europe"],
  ["el", "Ελληνικά", "Greek", "🇬🇷", "europe"],
  ["sr", "Српски", "Serbian", "🇷🇸", "europe"],
  ["hr", "Hrvatski", "Croatian", "🇭🇷", "europe"],
  ["bs", "Bosanski", "Bosnian", "🇧🇦", "europe"],
  ["sl", "Slovenščina", "Slovenian", "🇸🇮", "europe"],
  ["mk", "Македонски", "Macedonian", "🇲🇰", "europe"],
  ["sq", "Shqip", "Albanian", "🇦🇱", "europe"],
  ["mt", "Malti", "Maltese", "🇲🇹", "europe"],
  ["be", "Беларуская", "Belarusian", "🇧🇾", "europe"],
  ["lb", "Lëtzebuergesch", "Luxembourgish", "🇱🇺", "europe"],
  ["fy", "Frysk", "Frisian", "🇳🇱", "europe"],
  ["rm", "Rumantsch", "Romansh", "🇨🇭", "europe"],
  ["zh", "中文", "Chinese", "🇨🇳", "asia"],
  ["zh-HK", "中文 (香港)", "Chinese (Hong Kong)", "🇭🇰", "asia"],
  ["yue", "粵語", "Cantonese", "🇭🇰", "asia"],
  ["bo", "བོད་ཡིག", "Tibetan", "🇨🇳", "asia"],
  ["mn", "Монгол", "Mongolian", "🇲🇳", "asia"],
  ["kk", "Қазақ", "Kazakh", "🇰🇿", "asia"],
  ["uz", "Oʻzbek", "Uzbek", "🇺🇿", "asia"],
  ["ky", "Кыргызча", "Kyrgyz", "🇰🇬", "asia"],
  ["tg", "Тоҷикӣ", "Tajik", "🇹🇯", "asia"],
  ["tk", "Türkmen", "Turkmen", "🇹🇲", "asia"],
  ["az", "Azərbaycan", "Azerbaijani", "🇦🇿", "asia"],
  ["ka", "ქართული", "Georgian", "🇬🇪", "asia"],
  ["hy", "Հայերեն", "Armenian", "🇦🇲", "asia"],
  ["fa", "فارسی", "Persian", "🇮🇷", "asia"],
  ["ps", "پښتو", "Pashto", "🇦🇫", "asia"],
  ["ur", "اردو", "Urdu", "🇵🇰", "asia"],
  ["pa", "ਪੰਜਾਬੀ", "Punjabi", "🇮🇳", "asia"],
  ["bn", "বাংলা", "Bengali", "🇧🇩", "asia"],
  ["ta", "தமிழ்", "Tamil", "🇮🇳", "asia"],
  ["te", "తెలుగు", "Telugu", "🇮🇳", "asia"],
  ["kn", "ಕನ್ನಡ", "Kannada", "🇮🇳", "asia"],
  ["ml", "മലയാളം", "Malayalam", "🇮🇳", "asia"],
  ["mr", "मराठी", "Marathi", "🇮🇳", "asia"],
  ["gu", "ગુજરાતી", "Gujarati", "🇮🇳", "asia"],
  ["or", "ଓଡ଼ିଆ", "Odia", "🇮🇳", "asia"],
  ["as", "অসমীয়া", "Assamese", "🇮🇳", "asia"],
  ["ne", "नेपाली", "Nepali", "🇳🇵", "asia"],
  ["si", "සිංහල", "Sinhala", "🇱🇰", "asia"],
  ["my", "မြန်မာ", "Burmese", "🇲🇲", "asia"],
  ["km", "ខ្មែរ", "Khmer", "🇰🇭", "asia"],
  ["lo", "ລາວ", "Lao", "🇱🇦", "asia"],
  ["tl", "Filipino", "Filipino", "🇵🇭", "asia"],
  ["ceb", "Cebuano", "Cebuano", "🇵🇭", "asia"],
  ["jv", "Basa Jawa", "Javanese", "🇮🇩", "asia"],
  ["su", "Basa Sunda", "Sundanese", "🇮🇩", "asia"],
  ["am", "አማርኛ", "Amharic", "🇪🇹", "africa"],
  ["ti", "ትግርኛ", "Tigrinya", "🇪🇷", "africa"],
  ["om", "Oromoo", "Oromo", "🇪🇹", "africa"],
  ["so", "Soomaali", "Somali", "🇸🇴", "africa"],
  ["ha", "Hausa", "Hausa", "🇳🇬", "africa"],
  ["yo", "Yorùbá", "Yoruba", "🇳🇬", "africa"],
  ["ig", "Igbo", "Igbo", "🇳🇬", "africa"],
  ["zu", "isiZulu", "Zulu", "🇿🇦", "africa"],
  ["xh", "isiXhosa", "Xhosa", "🇿🇦", "africa"],
  ["af", "Afrikaans", "Afrikaans", "🇿🇦", "africa"],
  ["st", "Sesotho", "Southern Sotho", "🇱🇸", "africa"],
  ["tn", "Setswana", "Tswana", "🇧🇼", "africa"],
  ["sn", "chiShona", "Shona", "🇿🇼", "africa"],
  ["rw", "Kinyarwanda", "Kinyarwanda", "🇷🇼", "africa"],
  ["mg", "Malagasy", "Malagasy", "🇲🇬", "africa"],
  ["ny", "Chichewa", "Chichewa", "🇲🇼", "africa"],
  ["lg", "Luganda", "Ganda", "🇺🇬", "africa"],
  ["wo", "Wolof", "Wolof", "🇸🇳", "africa"],
  ["ff", "Fulfulde", "Fulah", "🇸🇳", "africa"],
  ["bm", "Bamanankan", "Bambara", "🇲🇱", "africa"],
  ["ee", "Eʋegbe", "Ewe", "🇬🇭", "africa"],
  ["ak", "Akan", "Akan", "🇬🇭", "africa"],
  ["ln", "Lingála", "Lingala", "🇨🇩", "africa"],
  ["kg", "Kikongo", "Kongo", "🇨🇩", "africa"],
  ["ar-EG", "العربية (مصر)", "Arabic (Egypt)", "🇪🇬", "middle-east"],
  ["ar-MA", "العربية (المغرب)", "Arabic (Morocco)", "🇲🇦", "middle-east"],
  ["ar-DZ", "العربية (الجزائر)", "Arabic (Algeria)", "🇩🇿", "middle-east"],
  ["ar-LB", "العربية (لبنان)", "Arabic (Lebanon)", "🇱🇧", "middle-east"],
  ["ar-JO", "العربية (الأردن)", "Arabic (Jordan)", "🇯🇴", "middle-east"],
  ["ar-AE", "العربية (الإمارات)", "Arabic (UAE)", "🇦🇪", "middle-east"],
  ["ar-SA", "العربية (السعودية)", "Arabic (Saudi Arabia)", "🇸🇦", "middle-east"],
  ["he", "עברית", "Hebrew", "🇮🇱", "middle-east"],
  ["ku", "Kurdî", "Kurdish", "🇮🇶", "middle-east"],
  ["dv", "ދިވެހި", "Dhivehi", "🇲🇻", "middle-east"],
  ["mi", "Te Reo Māori", "Maori", "🇳🇿", "oceania"],
  ["sm", "Gagana Samoa", "Samoan", "🇼🇸", "oceania"],
  ["to", "lea fakatonga", "Tongan", "🇹🇴", "oceania"],
  ["fj", "Na Vosa Vakaviti", "Fijian", "🇫🇯", "oceania"],
  ["haw", "ʻŌlelo Hawaiʻi", "Hawaiian", "🇺🇸", "oceania"],
  ["ty", "Reo Tahiti", "Tahitian", "🇵🇫", "oceania"],
  ["bi", "Bislama", "Bislama", "🇻🇺", "oceania"],
  ["tpi", "Tok Pisin", "Tok Pisin", "🇵🇬", "oceania"],
  ["eo", "Esperanto", "Esperanto", "🌐", "popular"],
  ["la", "Latina", "Latin", "🏛️", "europe"],
  ["sa", "संस्कृतम्", "Sanskrit", "🇮🇳", "asia"],
  ["yi", "ייִדיש", "Yiddish", "🇮🇱", "europe"],
  ["iu", "ᐃᓄᒃᑎᑐᑦ", "Inuktitut", "🇨🇦", "americas"],
  ["nv", "Diné Bizaad", "Navajo", "🇺🇸", "americas"],
  ["cr", "Nêhiyawêwin", "Cree", "🇨🇦", "americas"],
  ["oc", "Occitan", "Occitan", "🇫🇷", "europe"],
  ["br", "Brezhoneg", "Breton", "🇫🇷", "europe"],
  ["co", "Corsu", "Corsican", "🇫🇷", "europe"],
  ["sc", "Sardu", "Sardinian", "🇮🇹", "europe"],
  ["wa", "Walon", "Walloon", "🇧🇪", "europe"],
  ["fo", "Føroyskt", "Faroese", "🇫🇴", "europe"],
  ["kl", "Kalaallisut", "Greenlandic", "🇬🇱", "europe"],
  ["se", "Davvisámegiella", "Northern Sami", "🇳🇴", "europe"],
  ["tt", "Татар", "Tatar", "🇷🇺", "europe"],
  ["ba", "Башҡорт", "Bashkir", "🇷🇺", "europe"],
  ["cv", "Чăваш", "Chuvash", "🇷🇺", "europe"],
  ["ug", "ئۇيغۇرچە", "Uyghur", "🇨🇳", "asia"],
  ["dz", "རྫོང་ཁ", "Dzongkha", "🇧🇹", "asia"],
  ["sd", "سنڌي", "Sindhi", "🇵🇰", "asia"],
  ["ks", "کٲشُر", "Kashmiri", "🇮🇳", "asia"],
  ["bh", "भोजपुरी", "Bhojpuri", "🇮🇳", "asia"],
  ["mai", "मैथिली", "Maithili", "🇮🇳", "asia"],
  ["hne", "छत्तीसगढ़ी", "Chhattisgarhi", "🇮🇳", "asia"],
  ["sat", "ᱥᱟᱱᱛᱟᱲᱤ", "Santali", "🇮🇳", "asia"],
  ["mni", "Manipuri", "Manipuri", "🇮🇳", "asia"],
  ["doi", "Dogri", "Dogri", "🇮🇳", "asia"],
  ["kok", "Konkani", "Konkani", "🇮🇳", "asia"],
  ["bho", "भोजपुरी", "Bhojpuri", "🇮🇳", "asia"],
  ["awa", "Awadhi", "Awadhi", "🇮🇳", "asia"],
  ["mag", "मगही", "Magahi", "🇮🇳", "asia"],
  ["ilo", "Ilokano", "Ilocano", "🇵🇭", "asia"],
  ["war", "Winaray", "Waray", "🇵🇭", "asia"],
  ["pam", "Kapampangan", "Kapampangan", "🇵🇭", "asia"],
  ["ban", "Basa Bali", "Balinese", "🇮🇩", "asia"],
  ["min", "Baso Minangkabau", "Minangkabau", "🇮🇩", "asia"],
  ["ace", "Bahsa Acèh", "Acehnese", "🇮🇩", "asia"],
  ["bug", "Basa Ugi", "Buginese", "🇮🇩", "asia"],
  ["mad", "Madhura", "Madurese", "🇮🇩", "asia"],
  ["bcl", "Bikol", "Central Bikol", "🇵🇭", "asia"],
  ["hil", "Ilonggo", "Hiligaynon", "🇵🇭", "asia"],
  ["ve", "Tshivenḓa", "Venda", "🇿🇦", "africa"],
  ["ts", "Xitsonga", "Tsonga", "🇿🇦", "africa"],
  ["ss", "SiSwati", "Swati", "🇸🇿", "africa"],
  ["nr", "isiNdebele", "Southern Ndebele", "🇿🇦", "africa"],
  ["nso", "Sesotho sa Leboa", "Northern Sotho", "🇿🇦", "africa"],
  ["bem", "Ichibemba", "Bemba", "🇿🇲", "africa"],
  ["lua", "Tshiluba", "Luba-Kasai", "🇨🇩", "africa"],
  ["run", "Ikirundi", "Rundi", "🇧🇮", "africa"],
  ["sg", "Sängö", "Sango", "🇨🇫", "africa"]
];

export const roomLocaleRegionLabels: Record<RoomLocaleRegion, { en: string; es: string }> = {
  popular: { en: "Popular · auto-detect", es: "Popular · auto-detectar" },
  americas: { en: "Americas", es: "Américas" },
  europe: { en: "Europe", es: "Europa" },
  asia: { en: "Asia", es: "Asia" },
  africa: { en: "Africa", es: "África" },
  "middle-east": { en: "Middle East", es: "Medio Oriente" },
  oceania: { en: "Oceania", es: "Oceanía" }
};

function dedupeLanguages(rows: typeof languageRows): RoomLocaleOption[] {
  const seen = new Set<string>();
  const options: RoomLocaleOption[] = [];

  for (const [id, nativeLabel, englishLabel, flag, region] of rows) {
    const key = id.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    options.push({ id, nativeLabel, englishLabel, flag, region });
  }

  return options;
}

export const roomLocaleOptions: RoomLocaleOption[] = dedupeLanguages(languageRows);

export const roomLocaleIdSet = new Set(roomLocaleOptions.map((option) => option.id.toLowerCase()));

export function formatRoomLocaleOptionLabel(option: RoomLocaleOption) {
  return `${option.flag} ${option.nativeLabel}`;
}

export function formatRoomLocaleSearchText(option: RoomLocaleOption) {
  return `${option.id} ${option.nativeLabel} ${option.englishLabel} ${option.flag}`.toLowerCase();
}
