export const professionRankings = [
  {
    emoji: "👨‍⚕️",
    role: "Doctor",
    title: "Top AI",
    tools: ["ChatGPT", "Microsoft Copilot", "Gemini"],
    summary: "Compare AI for clinical notes, patient communication, workflow support, and medical research assistance.",
    countries: [
      { flag: "🇬🇧", name: "UK" },
      { flag: "🇨🇭", name: "Switzerland" },
      { flag: "🇮🇱", name: "Israel" },
      { flag: "🇯🇵", name: "Japan" },
      { flag: "🇺🇸", name: "USA" },
      { flag: "🇩🇪", name: "Germany" },
    ],
  },
  {
    emoji: "👩‍⚕️",
    role: "Nurse",
    title: "Top AI",
    tools: ["ChatGPT", "Nuance DAX", "Gemini"],
    summary: "AI for shift scheduling, patient handoff notes, medication tracking, care plans, and documentation.",
    countries: [
      { flag: "🇬🇧", name: "UK" },
      { flag: "🇺🇸", name: "USA" },
      { flag: "🇨🇦", name: "Canada" },
      { flag: "🇦🇺", name: "Australia" },
      { flag: "🇯🇵", name: "Japan" },
    ],
  },
  {
    emoji: "👨‍💻",
    role: "Programmer",
    title: "Top AI",
    tools: ["Claude", "ChatGPT", "GitHub Copilot", "Amazon Q", "Devin"],
    summary: "Discover coding copilots, debugging assistants, repo helpers, and engineering workflow tools.",
    countries: [
      { flag: "🇺🇸", name: "USA" },
      { flag: "🇮🇱", name: "Israel" },
      { flag: "🇨🇳", name: "China" },
      { flag: "🇯🇵", name: "Japan" },
      { flag: "🇮🇳", name: "India" },
      { flag: "🇬🇧", name: "UK" },
      { flag: "🇩🇪", name: "Germany" },
      { flag: "🇫🇷", name: "France" },
    ],
  },
  {
    emoji: "👩‍🍳",
    role: "Chef",
    title: "Top AI",
    tools: ["ChatGPT", "Gemini", "Claude"],
    summary: "Use AI for menu ideas, costing, prep planning, recipe variants, and restaurant operations.",
    countries: [
      { flag: "🇫🇷", name: "France" },
      { flag: "🇮🇹", name: "Italy" },
      { flag: "🇯🇵", name: "Japan" },
      { flag: "🇺🇸", name: "USA" },
      { flag: "🇪🇸", name: "Spain" },
    ],
  },
];

export const countryHubs = [
  {
    flag: "🇫🇷",
    name: "France",
    tag: "Open-Source & Large Models",
    description: "Mistral-style open model builders, multilingual fine-tuning, and private local deployments for European teams.",
    jobs: [
      { title: "Open-Source LLM Engineer", type: "Full-time", pay: "€70k–€110k", summary: "Fine-tune and deploy open-weight models for enterprise clients across Europe." },
      { title: "Multilingual AI Specialist", type: "Contract", pay: "€500–€1,200/day", summary: "Build multilingual NLP pipelines for French, EU, and African language markets." },
      { title: "AI Deployment Consultant", type: "Freelance", pay: "€80–€200/hr", summary: "On-premise AI setups for companies needing GDPR-compliant private hosting." },
    ],
  },
  {
    flag: "🇮🇱",
    name: "Israel",
    tag: "Deep Tech & AI Security",
    description: "Specialists in computer vision, AI-native SaaS, cybersecurity copilots, and enterprise integrations.",
    jobs: [
      { title: "Computer Vision Engineer", type: "Full-time", pay: "$120k–$180k", summary: "Build real-time vision systems for defense, healthcare, and industrial inspection." },
      { title: "AI Security Researcher", type: "Full-time", pay: "$100k–$160k", summary: "Red-team AI systems, find vulnerabilities, and build adversarial robustness." },
      { title: "AI Product Builder", type: "Startup", pay: "Equity + $90k–$140k", summary: "Found or join early-stage AI-native SaaS startups in Tel Aviv ecosystem." },
    ],
  },
  {
    flag: "🇬🇧",
    name: "United Kingdom",
    tag: "Enterprise Strategy & AI Safety",
    description: "Research-led AI services for fintech, compliance, healthcare workflows, and responsible deployment.",
    jobs: [
      { title: "AI Safety Researcher", type: "Full-time", pay: "£80k–£140k", summary: "Work on alignment, evals, and responsible AI frameworks for UK government and enterprise." },
      { title: "Healthcare AI Developer", type: "Contract", pay: "£500–£900/day", summary: "Build NHS-compatible clinical decision support and patient triage systems." },
      { title: "Fintech AI Engineer", type: "Full-time", pay: "£75k–£130k", summary: "Deploy fraud detection, credit scoring, and compliance automation for London fintechs." },
    ],
  },
  {
    flag: "🇪🇬",
    name: "Egypt",
    tag: "No-Code Automations & Chatbots",
    description: "Automation builders creating affordable operational systems, AI chat support, and workflow pipelines.",
    jobs: [
      { title: "n8n / Make Automation Builder", type: "Freelance", pay: "$300–$1,500/project", summary: "Build client automations, CRM integrations, and lead nurture flows." },
      { title: "AI Chatbot Developer", type: "Contract", pay: "$400–$2,000/project", summary: "Deploy WhatsApp, web, and Messenger chatbots for SMEs across MENA." },
      { title: "AI Virtual Assistant Provider", type: "Service", pay: "$200–$800/month", summary: "Offer managed AI assistant services for real estate, e-commerce, and support teams." },
    ],
  },
  {
    flag: "🇨🇳",
    name: "China",
    tag: "Creative Media & Mass Automation",
    description: "AI video, e-commerce automations, social commerce systems, and hardware-connected experiences.",
    jobs: [
      { title: "AI Video Producer", type: "Freelance", pay: "¥5k–¥20k/project", summary: "Generate product videos, social content, and ad creatives using AI tools." },
      { title: "E-Commerce AI Automator", type: "Full-time", pay: "¥20k–¥40k/month", summary: "Build automated listing, pricing, and customer service systems for Taobao and JD." },
      { title: "AI Hardware Integrator", type: "Contract", pay: "¥10k–¥30k/project", summary: "Connect AI models to smart devices, IoT systems, and robotics platforms." },
    ],
  },
  {
    flag: "🇯🇵",
    name: "Japan",
    tag: "Robotics & Agentic Workflows",
    description: "Structured multi-agent systems, robotics workflows, gaming AI logic, and precision tooling.",
    jobs: [
      { title: "Robotics AI Engineer", type: "Full-time", pay: "¥8M–¥15M/year", summary: "Build perception, planning, and control systems for service and industrial robots." },
      { title: "Multi-Agent Systems Developer", type: "Contract", pay: "¥800k–¥2M/project", summary: "Design agent orchestration frameworks for enterprise automation." },
      { title: "Game AI Programmer", type: "Full-time", pay: "¥6M–¥12M/year", summary: "Create NPC behavior, procedural content, and adaptive difficulty systems." },
    ],
  },
  {
    flag: "🇨🇭",
    name: "Switzerland",
    tag: "Data Privacy & FinTech AI",
    description: "Secure RAG systems, private hosting strategies, medical-grade data handling, and finance tooling.",
    jobs: [
      { title: "Privacy-First AI Architect", type: "Full-time", pay: "CHF 130k–CHF 200k", summary: "Design private inference pipelines and confidential computing AI systems." },
      { title: "Medical AI Developer", type: "Contract", pay: "CHF 1,000–CHF 1,800/day", summary: "Build HIPAA/GDPR-compliant clinical AI for Swiss hospitals and pharma." },
      { title: "FinTech ML Engineer", type: "Full-time", pay: "CHF 120k–CHF 180k", summary: "Deploy risk models, portfolio optimization, and regulatory AI for Zurich banks." },
    ],
  },
];

export const aiJobs = [
  {
    title: "AI Automation Builder",
    location: "Remote · Global",
    type: "Contract",
    pay: "$1,500 - $4,000 / project",
    summary: "Build workflow automations, connect tools, and deploy AI business systems for clients worldwide.",
  },
  {
    title: "Prompt Engineer",
    location: "Remote · Worldwide",
    type: "Freelance",
    pay: "$500 - $2,000 / package",
    summary: "Design tested prompt systems, prompt packs, and business-ready language workflows.",
  },
  {
    title: "AI Consultant",
    location: "Hybrid · International",
    type: "Monthly retainer",
    pay: "$1,000 - $8,000 / month",
    summary: "Advise companies on AI adoption, tool selection, workflow design, and deployment strategy.",
  },
  {
    title: "Custom AI App Developer",
    location: "Remote · Cross-border",
    type: "Project-based",
    pay: "$3,000 - $20,000 / build",
    summary: "Create AI dashboards, agents, internal tools, and product-ready client solutions.",
  },
];

export const revenueIdeas = [
  {
    title: "AI by profession rankings",
    money: "Affiliate revenue · sponsored placements · premium rankings",
    text: "Monetize profession pages with premium placement, tool recommendations, and comparison upgrades.",
  },
  {
    title: "Global AI marketplace",
    money: "Platform fees · paid listings · premium seller accounts",
    text: "Charge for visibility, transactions, and seller subscriptions across services and custom builds.",
  },
  {
    title: "AI jobs and hiring",
    money: "Paid job posts · recruiter access · boosted profiles",
    text: "Earn from employer listings, talent discovery, and premium hiring access.",
  },
  {
    title: "AI academy and memberships",
    money: "Courses · certificates · subscriptions · workshops",
    text: "Offer training, premium content, private groups, and career-focused AI education tracks.",
  },
];

export const healthcareCategories = [
  { icon: "🔬", label: "Medical research AI", tools: ["Elicit", "Consensus", "Semantic Scholar", "ChatGPT", "Gemini"] },
  { icon: "✍️", label: "Medical writing AI", tools: ["Claude", "ChatGPT", "Grammarly", "Jasper", "Writesonic"] },
  { icon: "🩻", label: "Medical imaging AI", tools: ["PathAI", "Aidoc", "Zebra Medical", "Viz.ai", "Arterys"] },
  { icon: "💊", label: "Drug interaction assistants", tools: ["Epocrates", "Medscape", "Clinical Pharmacology", "ChatGPT", "DrugBank"] },
  { icon: "📋", label: "Patient note assistants", tools: ["Nuance DAX", "Abridge", "Nabla", "Suki AI", "DeepScribe"] },
  { icon: "🌍", label: "Medical translators", tools: ["DeepL", "Google Translate", "ChatGPT", "MediLingua", "Systran"] },
];

export const studentSubjects = [
  {
    subject: "Math",
    emoji: "🔢",
    topAI: ["ChatGPT", "Wolfram Alpha", "Photomath", "Symbolab", "Mathway", "Microsoft Copilot", "Gemini", "Numerade", "Socratic", "Cymath"],
    freePaid: "Free & Paid",
    difficulty: "Beginner to Advanced",
    bestPrompts: "Solve step by step · Show proof · Explain like I'm 15 · Give practice problems",
    videoTutorials: "Professor Leonard, 3Blue1Brown, Khan Academy",
  },
  {
    subject: "Biology",
    emoji: "🧬",
    topAI: ["ChatGPT", "Gemini", "Claude", "Elicit", "Consensus", "Biology Flashcards AI", "Quizlet AI", "Coursera AI", "Khanmigo", "Labster"],
    freePaid: "Free & Paid",
    difficulty: "Beginner to Advanced",
    bestPrompts: "Explain this process · Create flashcards · Quiz me on Chapter 5 · Summarize this paper",
    videoTutorials: "Amoeba Sisters, CrashCourse Biology, Professor Dave",
  },
  {
    subject: "Chemistry",
    emoji: "⚗️",
    topAI: ["ChatGPT", "Wolfram Alpha", "Gemini", "MolView", "Chemistry by Design", "PubChem", "Claude", "Microsoft Copilot", "Khanmigo", "MasterOrganicChemistry"],
    freePaid: "Free & Paid",
    difficulty: "Intermediate to Advanced",
    bestPrompts: "Balance this equation · Explain this reaction mechanism · Draw the Lewis structure · Predict the product",
    videoTutorials: "Professor Dave, Tyler DeWitt, The Organic Chemistry Tutor",
  },
  {
    subject: "Physics",
    emoji: "⚛️",
    topAI: ["ChatGPT", "Wolfram Alpha", "Gemini", "Claude", "PhET Simulations", "Physics Classroom AI", "Microsoft Copilot", "Feynman Lectures AI", "Numerade", "Socratic"],
    freePaid: "Free & Paid",
    difficulty: "Intermediate to Advanced",
    bestPrompts: "Solve this problem step by step · Explain this concept · Give me a real-world example · Create practice exam",
    videoTutorials: "Walter Lewin, MinutePhysics, Veritasium,Physics Girl",
  },
  {
    subject: "Law",
    emoji: "⚖️",
    topAI: ["ChatGPT", "Claude", "Gemini", "Lexis+ AI", "CoCounsel", "Westlaw Edge", "Casetext", "Microsoft Copilot", "Perplexity", "Harvey AI"],
    freePaid: "Mostly Paid",
    difficulty: "Advanced",
    bestPrompts: "Summarize this case · Explain this legal concept · Compare these statutes · Draft a clause for...",
    videoTutorials: "LegalEagle, LawShelf, Harvard Online",
  },
  {
    subject: "Nursing",
    emoji: "🩺",
    topAI: ["ChatGPT", "Nuance DAX", "Gemini", "Picmonic", "SimpleNursing", "UWorld", "Claude", "Nursing.com", "Study.com", "Microsoft Copilot"],
    freePaid: "Free & Paid",
    difficulty: "Beginner to Advanced",
    bestPrompts: "Explain this diagnosis · Create care plan for · Quiz me on pharmacology · Summarize this patient scenario",
    videoTutorials: "SimpleNursing, RegisteredNurseRN, LevelUpRN",
  },
  {
    subject: "Engineering",
    emoji: "🏗️",
    topAI: ["ChatGPT", "Claude", "Gemini", "MATLAB Copilot", "Autodesk AI", "SolidWorks AI", "Wolfram Alpha", "Microsoft Copilot", "ANSYS AI", "Coursera AI"],
    freePaid: "Free & Paid",
    difficulty: "Intermediate to Advanced",
    bestPrompts: "Check this calculation · Explain this concept · Suggest design improvements · Generate MATLAB code for...",
    videoTutorials: "Engineering Mindset, Real Engineering, MIT OpenCourseWare",
  },
  {
    subject: "Programming",
    emoji: "💻",
    topAI: ["Claude", "ChatGPT", "GitHub Copilot", "Amazon Q", "Devin", "Cursor", "Windsurf", "Replit AI", "Codeium", "Tabnine"],
    freePaid: "Free & Paid",
    difficulty: "Beginner to Advanced",
    bestPrompts: "Write a function that · Debug this code · Explain this error · Refactor this for readability · Write tests for",
    videoTutorials: "Fireship, Traversy Media, The Odin Project, freeCodeCamp",
  },
  {
    subject: "Architecture",
    emoji: "🏛️",
    topAI: ["ChatGPT", "Midjourney", "DALL·E", "Gemini", "Autodesk AI", "Stable Diffusion", "Claude", "Veras", "PromeAI", "Microsoft Copilot"],
    freePaid: "Free & Paid",
    difficulty: "Intermediate to Advanced",
    bestPrompts: "Generate a floor plan for · Render this in modern style · Suggest sustainable materials · Create elevation views",
    videoTutorials: "Show It Better, Architectural Digest, 30X40 Design",
  },
  {
    subject: "Accounting",
    emoji: "📊",
    topAI: ["ChatGPT", "Claude", "Gemini", "Vic.ai", "Botkeeper", "Stampli", "Microsoft Copilot", "QuickBooks AI", "Xero AI", "Sage AI"],
    freePaid: "Mostly Paid",
    difficulty: "Beginner to Advanced",
    bestPrompts: "Reconcile this transaction · Explain this tax rule · Create a budget for · Summarize this financial report",
    videoTutorials: "Edspira, Accounting Stuff, CPA Strength",
  },
  {
    subject: "Economics",
    emoji: "📈",
    topAI: ["ChatGPT", "Gemini", "Claude", "FRED AI", "EconLit", "Microsoft Copilot", "Wolfram Alpha", "Perplexity", "Coursera AI", "Khan Academy AI"],
    freePaid: "Free & Paid",
    difficulty: "Intermediate to Advanced",
    bestPrompts: "Explain this economic model · Analyze this data set · Compare these theories · Predict market impact of...",
    videoTutorials: "Marginal Revolution University, Khan Academy, Economics Explained",
  },
  {
    subject: "Languages",
    emoji: "🗣️",
    topAI: ["Duolingo Max", "ChatGPT", "DeepL", "Gemini", "Babbel", "Rosetta Stone AI", "Busuu", "Microsoft Copilot", "HelloTalk AI", "Clozemaster"],
    freePaid: "Free & Paid",
    difficulty: "Beginner to Advanced",
    bestPrompts: "Translate this paragraph · Correct my grammar · Teach me conversational · Create flashcards for vocabulary",
    videoTutorials: "Easy Languages, Language Simp, Comprehensible Input",
  },
];

export const allCareers = [
  { emoji: "👨‍⚕️", role: "Doctor" },
  { emoji: "👩‍⚕️", role: "Nurse" },
  { emoji: "👨‍💻", role: "Programmer" },
  { emoji: "👩‍🍳", role: "Chef" },
  { emoji: "👩‍🏫", role: "Teacher" },
  { emoji: "⚖️", role: "Lawyer" },
  { emoji: "🏗️", role: "Engineer" },
  { emoji: "🔧", role: "Mechanic" },
  { emoji: "🌾", role: "Farmer" },
  { emoji: "🚕", role: "Taxi Driver" },
  { emoji: "🔨", role: "Construction Worker" },
  { emoji: "🎨", role: "Designer" },
  { emoji: "✍️", role: "Writer" },
  { emoji: "🏪", role: "Small Business Owner" },
  { emoji: "🏠", role: "Real Estate Agent" },
  { emoji: "📊", role: "Accountant" },
  { emoji: "🚗", role: "Electrician" },
  { emoji: "✈️", role: "Pilot" },
  { emoji: "🦷", role: "Dentist" },
  { emoji: "🎵", role: "Musician" },
  { emoji: "🔬", role: "Scientist" },
  { emoji: "👮", role: "Police" },
  { emoji: "🧑‍🚒", role: "Firefighter" },
  { emoji: "🏨", role: "Hotel Owner" },
  { emoji: "🌍", role: "Tour Guide" },
  { emoji: "🛠️", role: "Construction" },
  { emoji: "👷", role: "Electrician" },
];

export const ecommerceTools = [
  { category: "AI product title generator", icon: "🏷️", tools: ["ChatGPT", "Jasper", "Copy.ai", "Writesonic", "Gemini"], description: "Generate optimized product titles for SEO and conversions." },
  { category: "AI description generator", icon: "📝", tools: ["ChatGPT", "Jasper", "Copy.ai", "Rytr", "Claude"], description: "Write compelling product descriptions that sell." },
  { category: "AI ad copy generator", icon: "📢", tools: ["AdCreative.ai", "Jasper", "ChatGPT", "Copy.ai", "Anyword"], description: "Create high-converting ad copy for Facebook, Google, and TikTok." },
  { category: "AI logo creator", icon: "🎨", tools: ["Looka", "Midjourney", "DALL·E", "Brandmark", "Tailor Brands"], description: "Design professional logos without a designer." },
  { category: "AI store builder", icon: "🛒", tools: ["Shopify AI", "Wix AI", "Hostinger AI", "Zyro", "Framer"], description: "Build complete online stores with AI-assisted design." },
  { category: "AI customer support", icon: "💬", tools: ["Tidio AI", "Intercom Fin", "Zendesk AI", "ChatGPT API", "Crisp AI"], description: "Automate customer support with intelligent chatbots." },
];

export const affiliatePrograms = [
  { name: "ChatGPT Plus", commission: "20%", cookie: "30 days", link: "openai.com/affiliates" },
  { name: "Jasper AI", commission: "30%", cookie: "30 days", link: "jasper.ai/affiliates" },
  { name: "Copy.ai", commission: "30%", cookie: "60 days", link: "copy.ai/affiliates" },
  { name: "Midjourney", commission: "20%", cookie: "30 days", link: "midjourney.com" },
  { name: "Notion AI", commission: "25%", cookie: "90 days", link: "notion.so/affiliates" },
  { name: "Canva Pro", commission: "15%", cookie: "30 days", link: "canva.com/affiliates" },
  { name: "Duolingo Max", commission: "25%", cookie: "30 days", link: "duolingo.com/affiliates" },
  { name: "Grammarly", commission: "20%", cookie: "45 days", link: "grammarly.com/affiliates" },
];

export const freelanceServices = [
  { service: "AI content writing", emoji: "✍️", price: "$50–$500/project", difficulty: "Beginner" },
  { service: "Logo design", emoji: "🎨", price: "$100–$1,000/project", difficulty: "Beginner" },
  { service: "Website creation", emoji: "🌐", price: "$500–$5,000/project", difficulty: "Intermediate" },
  { service: "Video editing", emoji: "🎬", price: "$200–$2,000/project", difficulty: "Intermediate" },
  { service: "AI automation setup", emoji: "⚙️", price: "$300–$3,000/project", difficulty: "Advanced" },
  { service: "Resume writing", emoji: "📄", price: "$50–$300/project", difficulty: "Beginner" },
];

export const promptMarketplace = [
  { category: "Prompt packs", icon: "📦", examples: ["ChatGPT prompts for marketers", "Midjourney style prompts", "Business automation prompts"] },
  { category: "Templates", icon: "📋", examples: ["Email templates", "Social media templates", "Business plan templates"] },
  { category: "Workflows", icon: "🔄", examples: ["Lead nurture sequences", "Content calendar workflows", "Customer onboarding flows"] },
  { category: "Business automation", icon: "🤖", examples: ["n8n workflow packs", "Make.com blueprints", "Zapier automation sets"] },
  { category: "Educational collections", icon: "📚", examples: ["Study prompt packs", "Research prompts", "Writing improvement prompts"] },
];
